# Generated by Django 4.0.6 on 2022-08-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsslider',
            name='cms_text',
            field=models.CharField(default='text', max_length=200, verbose_name='Текст'),
        ),
    ]
