# Generated by Django 4.0.6 on 2022-08-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_cmsslider_cms_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsslider',
            name='cms_css',
            field=models.CharField(default='css', max_length=200, null=True, verbose_name='CSS класс'),
        ),
    ]
